// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: rkl-test1-SquareLine_Project

#ifndef _RKL_TEST1_SQUARELINE_PROJECT_UI_H
#define _RKL_TEST1_SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_RootPanel;
void ui_event_TopButton11(lv_event_t * e);
extern lv_obj_t * ui_TopButton11;
void ui_event_TopButton12(lv_event_t * e);
extern lv_obj_t * ui_TopButton12;
void ui_event_TopButton13(lv_event_t * e);
extern lv_obj_t * ui_TopButton13;
extern lv_obj_t * ui_Panel_Header1;
extern lv_obj_t * ui_Label_Header1;
extern lv_obj_t * ui_IMG_Wifi1;
extern lv_obj_t * ui_IMG_PC1;
extern lv_obj_t * ui_IMG_USB1;
extern lv_obj_t * ui_TopPanel;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_MainTempPanel;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_TempGraph;
extern lv_obj_t * ui_TempChart;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_RootPanel1;
void ui_event_TopButton21(lv_event_t * e);
extern lv_obj_t * ui_TopButton21;
void ui_event_TopButton22(lv_event_t * e);
extern lv_obj_t * ui_TopButton22;
void ui_event_TopButton23(lv_event_t * e);
extern lv_obj_t * ui_TopButton23;
extern lv_obj_t * ui_Panel_Header2;
extern lv_obj_t * ui_Label_Header2;
extern lv_obj_t * ui_IMG_Wifi2;
extern lv_obj_t * ui_IMG_PC2;
extern lv_obj_t * ui_IMG_USB2;
extern lv_obj_t * ui_TopPanel1;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_MainTempPanel1;
extern lv_obj_t * ui_Temp1;
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_PanelTemp5;
extern lv_obj_t * ui_TextTemp5;
extern lv_obj_t * ui_PanelTemp6;
extern lv_obj_t * ui_TextTemp6;
extern lv_obj_t * ui_PanelTemp7;
extern lv_obj_t * ui_TextTemp7;
extern lv_obj_t * ui_PanelTemp8;
extern lv_obj_t * ui_TextTemp8;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_RootPanel2;
void ui_event_TopButton31(lv_event_t * e);
extern lv_obj_t * ui_TopButton31;
void ui_event_TopButton32(lv_event_t * e);
extern lv_obj_t * ui_TopButton32;
void ui_event_TopButton33(lv_event_t * e);
extern lv_obj_t * ui_TopButton33;
extern lv_obj_t * ui_Panel_Header3;
extern lv_obj_t * ui_Label_Header3;
extern lv_obj_t * ui_IMG_Wifi3;
extern lv_obj_t * ui_IMG_PC3;
extern lv_obj_t * ui_IMG_USB3;
extern lv_obj_t * ui_TopPanel2;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_MainSensorSelectRoller;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_DSTCheckbox;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_emon_disp_bg_png);    // assets\emon_disp_bg.png
LV_IMG_DECLARE(ui_img_icn_wifi_png);    // assets\icn_wifi.png
LV_IMG_DECLARE(ui_img_588575976);    // assets\185092_clock_time_icon-grey.png
LV_IMG_DECLARE(ui_img_icn_usb_png);    // assets\icn_usb.png
LV_IMG_DECLARE(ui_img_btn_print_top_off_png);    // assets\btn_print_top_off.png

LV_FONT_DECLARE(ui_font_displayRobot128B);
LV_FONT_DECLARE(ui_font_displayRobot164B);
LV_FONT_DECLARE(ui_font_displayRobot24);
LV_FONT_DECLARE(ui_font_displayRobot256B);
LV_FONT_DECLARE(ui_font_displayRoboto16);
LV_FONT_DECLARE(ui_font_displayRoboto18);
LV_FONT_DECLARE(ui_font_displayRoboto18M);
LV_FONT_DECLARE(ui_font_displayRoboto24);
LV_FONT_DECLARE(ui_font_displayRoboto48);
LV_FONT_DECLARE(ui_font_displayRoboto72);
LV_FONT_DECLARE(ui_font_displayRoboto96);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
