// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: rkl-test1-SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x263436), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image1, &ui_img_emon_disp_bg_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RootPanel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_RootPanel1, 800);
    lv_obj_set_height(ui_RootPanel1, 480);
    lv_obj_set_x(ui_RootPanel1, 2);
    lv_obj_set_y(ui_RootPanel1, -1);
    lv_obj_set_align(ui_RootPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RootPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RootPanel1, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopButton21 = lv_btn_create(ui_RootPanel1);
    lv_obj_set_width(ui_TopButton21, 55);
    lv_obj_set_height(ui_TopButton21, 73);
    lv_obj_set_x(ui_TopButton21, -363);
    lv_obj_set_y(ui_TopButton21, -153);
    lv_obj_set_align(ui_TopButton21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopButton21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TopButton21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopButton21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopButton21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopButton22 = lv_btn_create(ui_RootPanel1);
    lv_obj_set_width(ui_TopButton22, 66);
    lv_obj_set_height(ui_TopButton22, 82);
    lv_obj_set_x(ui_TopButton22, -362);
    lv_obj_set_y(ui_TopButton22, 12);
    lv_obj_set_align(ui_TopButton22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopButton22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TopButton22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopButton22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopButton22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopButton23 = lv_btn_create(ui_RootPanel1);
    lv_obj_set_width(ui_TopButton23, 66);
    lv_obj_set_height(ui_TopButton23, 82);
    lv_obj_set_x(ui_TopButton23, -364);
    lv_obj_set_y(ui_TopButton23, 161);
    lv_obj_set_align(ui_TopButton23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopButton23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TopButton23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopButton23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopButton23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Header2 = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_Panel_Header2, 665);
    lv_obj_set_height(ui_Panel_Header2, 39);
    lv_obj_set_x(ui_Panel_Header2, -9);
    lv_obj_set_y(ui_Panel_Header2, -20);
    lv_obj_set_align(ui_Panel_Header2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header2 = lv_label_create(ui_Panel_Header2);
    lv_obj_set_width(ui_Label_Header2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header2, "Press the control buttons");
    lv_label_set_recolor(ui_Label_Header2, "true");
    lv_obj_set_style_text_color(ui_Label_Header2, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header2, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Wifi2 = lv_img_create(ui_Panel_Header2);
    lv_img_set_src(ui_IMG_Wifi2, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_IMG_Wifi2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Wifi2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IMG_Wifi2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_Wifi2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_IMG_PC2 = lv_img_create(ui_Panel_Header2);
    lv_img_set_src(ui_IMG_PC2, &ui_img_588575976);
    lv_obj_set_width(ui_IMG_PC2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_PC2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_PC2, -42);
    lv_obj_set_y(ui_IMG_PC2, 0);
    lv_obj_set_align(ui_IMG_PC2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_PC2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_IMG_USB2 = lv_img_create(ui_Panel_Header2);
    lv_img_set_src(ui_IMG_USB2, &ui_img_icn_usb_png);
    lv_obj_set_width(ui_IMG_USB2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_USB2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_USB2, -84);
    lv_obj_set_y(ui_IMG_USB2, 0);
    lv_obj_set_align(ui_IMG_USB2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_USB2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_TopPanel1 = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_TopPanel1, 760);
    lv_obj_set_height(ui_TopPanel1, 40);
    lv_obj_set_x(ui_TopPanel1, 0);
    lv_obj_set_y(ui_TopPanel1, -212);
    lv_obj_set_align(ui_TopPanel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopPanel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TopPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopPanel1, lv_color_hex(0x05636D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TopPanel1, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea3 = lv_textarea_create(ui_TopPanel1);
    lv_obj_set_width(ui_TextArea3, 700);
    lv_obj_set_height(ui_TextArea3, 54);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea3, "Clock");
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea3, lv_color_hex(0xE9C24E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea3, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea3, lv_color_hex(0x05636D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_MainTempPanel1 = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_MainTempPanel1, 668);
    lv_obj_set_height(ui_MainTempPanel1, 169);
    lv_obj_set_x(ui_MainTempPanel1, 34);
    lv_obj_set_y(ui_MainTempPanel1, -97);
    lv_obj_set_align(ui_MainTempPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainTempPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainTempPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainTempPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainTempPanel1, lv_color_hex(0x5F4C10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainTempPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainTempPanel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainTempPanel1, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp1 = lv_obj_create(ui_MainTempPanel1);
    lv_obj_set_width(ui_Temp1, 239);
    lv_obj_set_height(ui_Temp1, 182);
    lv_obj_set_x(ui_Temp1, -201);
    lv_obj_set_y(ui_Temp1, 14);
    lv_obj_set_align(ui_Temp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Temp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Temp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Temp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp1, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea4 = lv_textarea_create(ui_Temp1);
    lv_obj_set_width(ui_TextArea4, 220);
    lv_obj_set_height(ui_TextArea4, 181);
    lv_obj_set_x(ui_TextArea4, 7);
    lv_obj_set_y(ui_TextArea4, -7);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea4, "24");
    lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea4, &ui_font_displayRobot164B, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea4, lv_color_hex(0x226633), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_TextArea4, &ui_font_displayRoboto96, LV_PART_SELECTED | LV_STATE_DEFAULT);


    ui_PanelTemp5 = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_PanelTemp5, 110);
    lv_obj_set_height(ui_PanelTemp5, 111);
    lv_obj_set_x(ui_PanelTemp5, -238);
    lv_obj_set_y(ui_PanelTemp5, 182);
    lv_obj_set_align(ui_PanelTemp5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTemp5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTemp5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemp5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelTemp5, &ui_img_btn_print_top_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelTemp5, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextTemp5 = lv_textarea_create(ui_PanelTemp5);
    lv_obj_set_width(ui_TextTemp5, 113);
    lv_obj_set_height(ui_TextTemp5, 107);
    lv_obj_set_align(ui_TextTemp5, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextTemp5, "56");
    lv_textarea_set_placeholder_text(ui_TextTemp5, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextTemp5, lv_color_hex(0xF6EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextTemp5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextTemp5, &ui_font_displayRoboto72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextTemp5, lv_color_hex(0x226633), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextTemp5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_font(ui_TextTemp5, &ui_font_displayRoboto24, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_PanelTemp6 = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_PanelTemp6, 120);
    lv_obj_set_height(ui_PanelTemp6, 113);
    lv_obj_set_x(ui_PanelTemp6, -57);
    lv_obj_set_y(ui_PanelTemp6, 185);
    lv_obj_set_align(ui_PanelTemp6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTemp6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTemp6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemp6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelTemp6, &ui_img_btn_print_top_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelTemp6, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextTemp6 = lv_textarea_create(ui_PanelTemp6);
    lv_obj_set_width(ui_TextTemp6, 113);
    lv_obj_set_height(ui_TextTemp6, 107);
    lv_obj_set_align(ui_TextTemp6, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextTemp6, "56");
    lv_textarea_set_placeholder_text(ui_TextTemp6, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextTemp6, lv_color_hex(0xF6EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextTemp6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextTemp6, &ui_font_displayRoboto72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextTemp6, lv_color_hex(0x226633), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextTemp6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_font(ui_TextTemp6, &ui_font_displayRoboto24, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_PanelTemp7 = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_PanelTemp7, 120);
    lv_obj_set_height(ui_PanelTemp7, 113);
    lv_obj_set_x(ui_PanelTemp7, 133);
    lv_obj_set_y(ui_PanelTemp7, 184);
    lv_obj_set_align(ui_PanelTemp7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTemp7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTemp7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemp7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelTemp7, &ui_img_btn_print_top_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelTemp7, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextTemp7 = lv_textarea_create(ui_PanelTemp7);
    lv_obj_set_width(ui_TextTemp7, 113);
    lv_obj_set_height(ui_TextTemp7, 107);
    lv_obj_set_align(ui_TextTemp7, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextTemp7, "56");
    lv_textarea_set_placeholder_text(ui_TextTemp7, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextTemp7, lv_color_hex(0xF6EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextTemp7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextTemp7, &ui_font_displayRoboto72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextTemp7, lv_color_hex(0x226633), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextTemp7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_font(ui_TextTemp7, &ui_font_displayRoboto24, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_PanelTemp8 = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_PanelTemp8, 120);
    lv_obj_set_height(ui_PanelTemp8, 113);
    lv_obj_set_x(ui_PanelTemp8, 313);
    lv_obj_set_y(ui_PanelTemp8, 184);
    lv_obj_set_align(ui_PanelTemp8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTemp8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTemp8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemp8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelTemp8, &ui_img_btn_print_top_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelTemp8, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextTemp8 = lv_textarea_create(ui_PanelTemp8);
    lv_obj_set_width(ui_TextTemp8, 113);
    lv_obj_set_height(ui_TextTemp8, 107);
    lv_obj_set_align(ui_TextTemp8, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextTemp8, "56");
    lv_textarea_set_placeholder_text(ui_TextTemp8, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextTemp8, lv_color_hex(0xF6EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextTemp8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextTemp8, &ui_font_displayRoboto72, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextTemp8, lv_color_hex(0x226633), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextTemp8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_font(ui_TextTemp8, &ui_font_displayRoboto24, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TopButton21, ui_event_TopButton21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TopButton22, ui_event_TopButton22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TopButton23, ui_event_TopButton23, LV_EVENT_ALL, NULL);

}
