// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: rkl-test1-SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x263436), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image2, &ui_img_emon_disp_bg_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RootPanel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_RootPanel2, 800);
    lv_obj_set_height(ui_RootPanel2, 480);
    lv_obj_set_x(ui_RootPanel2, -9);
    lv_obj_set_y(ui_RootPanel2, -5);
    lv_obj_set_align(ui_RootPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RootPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RootPanel2, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopButton31 = lv_btn_create(ui_RootPanel2);
    lv_obj_set_width(ui_TopButton31, 55);
    lv_obj_set_height(ui_TopButton31, 73);
    lv_obj_set_x(ui_TopButton31, -363);
    lv_obj_set_y(ui_TopButton31, -153);
    lv_obj_set_align(ui_TopButton31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopButton31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TopButton31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopButton31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopButton31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopButton32 = lv_btn_create(ui_RootPanel2);
    lv_obj_set_width(ui_TopButton32, 66);
    lv_obj_set_height(ui_TopButton32, 82);
    lv_obj_set_x(ui_TopButton32, -362);
    lv_obj_set_y(ui_TopButton32, 12);
    lv_obj_set_align(ui_TopButton32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopButton32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TopButton32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopButton32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopButton32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopButton33 = lv_btn_create(ui_RootPanel2);
    lv_obj_set_width(ui_TopButton33, 66);
    lv_obj_set_height(ui_TopButton33, 82);
    lv_obj_set_x(ui_TopButton33, -365);
    lv_obj_set_y(ui_TopButton33, 161);
    lv_obj_set_align(ui_TopButton33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopButton33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TopButton33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopButton33, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopButton33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Header3 = lv_obj_create(ui_RootPanel2);
    lv_obj_set_width(ui_Panel_Header3, 665);
    lv_obj_set_height(ui_Panel_Header3, 39);
    lv_obj_set_x(ui_Panel_Header3, -9);
    lv_obj_set_y(ui_Panel_Header3, -20);
    lv_obj_set_align(ui_Panel_Header3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header3 = lv_label_create(ui_Panel_Header3);
    lv_obj_set_width(ui_Label_Header3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header3, "Press the control buttons");
    lv_label_set_recolor(ui_Label_Header3, "true");
    lv_obj_set_style_text_color(ui_Label_Header3, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header3, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Wifi3 = lv_img_create(ui_Panel_Header3);
    lv_img_set_src(ui_IMG_Wifi3, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_IMG_Wifi3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Wifi3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IMG_Wifi3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_Wifi3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_IMG_PC3 = lv_img_create(ui_Panel_Header3);
    lv_img_set_src(ui_IMG_PC3, &ui_img_588575976);
    lv_obj_set_width(ui_IMG_PC3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_PC3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_PC3, -42);
    lv_obj_set_y(ui_IMG_PC3, 0);
    lv_obj_set_align(ui_IMG_PC3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_PC3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_IMG_USB3 = lv_img_create(ui_Panel_Header3);
    lv_img_set_src(ui_IMG_USB3, &ui_img_icn_usb_png);
    lv_obj_set_width(ui_IMG_USB3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_USB3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_USB3, -84);
    lv_obj_set_y(ui_IMG_USB3, 0);
    lv_obj_set_align(ui_IMG_USB3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_USB3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_TopPanel2 = lv_obj_create(ui_RootPanel2);
    lv_obj_set_width(ui_TopPanel2, 760);
    lv_obj_set_height(ui_TopPanel2, 40);
    lv_obj_set_x(ui_TopPanel2, 0);
    lv_obj_set_y(ui_TopPanel2, -212);
    lv_obj_set_align(ui_TopPanel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopPanel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TopPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopPanel2, lv_color_hex(0x05636D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TopPanel2, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea5 = lv_textarea_create(ui_TopPanel2);
    lv_obj_set_width(ui_TextArea5, 700);
    lv_obj_set_height(ui_TextArea5, 54);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea5, "Clock");
    lv_textarea_set_placeholder_text(ui_TextArea5, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea5, lv_color_hex(0xE9C24E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea5, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea5, lv_color_hex(0x05636D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_MainSensorSelectRoller = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_MainSensorSelectRoller,
                          "sensor 1\nsensor 2\nsensor 3\nsensor 4\nsensor 5\nsensor 6\nsensor 7\nsensor 8\nsensor 9\nsensor 10\nsensor 11\nsensor 12",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_MainSensorSelectRoller, 239);
    lv_obj_set_width(ui_MainSensorSelectRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MainSensorSelectRoller, -216);
    lv_obj_set_y(ui_MainSensorSelectRoller, 44);
    lv_obj_set_align(ui_MainSensorSelectRoller, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -222);
    lv_obj_set_y(ui_Label1, -104);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "main sensor");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DSTCheckbox = lv_checkbox_create(ui_Screen3);
    lv_checkbox_set_text(ui_DSTCheckbox, "Daylight saving on");
    lv_obj_set_width(ui_DSTCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DSTCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DSTCheckbox, 69);
    lv_obj_set_y(ui_DSTCheckbox, -96);
    lv_obj_set_align(ui_DSTCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DSTCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_TopButton31, ui_event_TopButton31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TopButton32, ui_event_TopButton32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TopButton33, ui_event_TopButton33, LV_EVENT_ALL, NULL);

}
