// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: rkl-test1-SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x263436), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_emon_disp_bg_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RootPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RootPanel, 800);
    lv_obj_set_height(ui_RootPanel, 480);
    lv_obj_set_x(ui_RootPanel, 2);
    lv_obj_set_y(ui_RootPanel, -1);
    lv_obj_set_align(ui_RootPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RootPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RootPanel, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopButton11 = lv_btn_create(ui_RootPanel);
    lv_obj_set_width(ui_TopButton11, 65);
    lv_obj_set_height(ui_TopButton11, 71);
    lv_obj_set_x(ui_TopButton11, -363);
    lv_obj_set_y(ui_TopButton11, -160);
    lv_obj_set_align(ui_TopButton11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopButton11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TopButton11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopButton11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopButton11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopButton12 = lv_btn_create(ui_RootPanel);
    lv_obj_set_width(ui_TopButton12, 65);
    lv_obj_set_height(ui_TopButton12, 71);
    lv_obj_set_x(ui_TopButton12, -364);
    lv_obj_set_y(ui_TopButton12, 2);
    lv_obj_set_align(ui_TopButton12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopButton12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TopButton12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopButton12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopButton12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopButton13 = lv_btn_create(ui_RootPanel);
    lv_obj_set_width(ui_TopButton13, 65);
    lv_obj_set_height(ui_TopButton13, 71);
    lv_obj_set_x(ui_TopButton13, -366);
    lv_obj_set_y(ui_TopButton13, 164);
    lv_obj_set_align(ui_TopButton13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopButton13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TopButton13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopButton13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopButton13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Header1 = lv_obj_create(ui_RootPanel);
    lv_obj_set_width(ui_Panel_Header1, 665);
    lv_obj_set_height(ui_Panel_Header1, 39);
    lv_obj_set_x(ui_Panel_Header1, -9);
    lv_obj_set_y(ui_Panel_Header1, -20);
    lv_obj_set_align(ui_Panel_Header1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header1 = lv_label_create(ui_Panel_Header1);
    lv_obj_set_width(ui_Label_Header1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header1, "Press the control buttons");
    lv_label_set_recolor(ui_Label_Header1, "true");
    lv_obj_set_style_text_color(ui_Label_Header1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header1, &ui_font_displayRobot24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Wifi1 = lv_img_create(ui_Panel_Header1);
    lv_img_set_src(ui_IMG_Wifi1, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_IMG_Wifi1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Wifi1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IMG_Wifi1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_Wifi1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_IMG_PC1 = lv_img_create(ui_Panel_Header1);
    lv_img_set_src(ui_IMG_PC1, &ui_img_588575976);
    lv_obj_set_width(ui_IMG_PC1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_PC1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_PC1, -42);
    lv_obj_set_y(ui_IMG_PC1, 0);
    lv_obj_set_align(ui_IMG_PC1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_PC1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_IMG_USB1 = lv_img_create(ui_Panel_Header1);
    lv_img_set_src(ui_IMG_USB1, &ui_img_icn_usb_png);
    lv_obj_set_width(ui_IMG_USB1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_USB1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_USB1, -84);
    lv_obj_set_y(ui_IMG_USB1, 0);
    lv_obj_set_align(ui_IMG_USB1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_USB1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_TopPanel = lv_obj_create(ui_RootPanel);
    lv_obj_set_width(ui_TopPanel, 760);
    lv_obj_set_height(ui_TopPanel, 40);
    lv_obj_set_x(ui_TopPanel, 0);
    lv_obj_set_y(ui_TopPanel, -212);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TopPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x05636D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TopPanel, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_TopPanel);
    lv_obj_set_width(ui_TextArea1, 700);
    lv_obj_set_height(ui_TextArea1, 54);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "Clock");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xE9C24E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x05636D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_MainTempPanel = lv_obj_create(ui_RootPanel);
    lv_obj_set_width(ui_MainTempPanel, 668);
    lv_obj_set_height(ui_MainTempPanel, 421);
    lv_obj_set_x(ui_MainTempPanel, 37);
    lv_obj_set_y(ui_MainTempPanel, 22);
    lv_obj_set_align(ui_MainTempPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainTempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainTempPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainTempPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainTempPanel, lv_color_hex(0x5F4C10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainTempPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainTempPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainTempPanel, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp = lv_obj_create(ui_MainTempPanel);
    lv_obj_set_width(ui_Temp, 372);
    lv_obj_set_height(ui_Temp, 231);
    lv_obj_set_x(ui_Temp, -25);
    lv_obj_set_y(ui_Temp, -104);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp, &ui_font_displayRoboto24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Temp);
    lv_obj_set_width(ui_TextArea2, 382);
    lv_obj_set_height(ui_TextArea2, 254);
    lv_obj_set_x(ui_TextArea2, 61);
    lv_obj_set_y(ui_TextArea2, 8);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea2, "24");
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea2, &ui_font_displayRobot256B, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0x226633), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_TextArea2, &ui_font_displayRoboto96, LV_PART_SELECTED | LV_STATE_DEFAULT);


    ui_TempGraph = lv_obj_create(ui_MainTempPanel);
    lv_obj_set_width(ui_TempGraph, 712);
    lv_obj_set_height(ui_TempGraph, 203);
    lv_obj_set_x(ui_TempGraph, 2);
    lv_obj_set_y(ui_TempGraph, 106);
    lv_obj_set_align(ui_TempGraph, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempGraph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempGraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempGraph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TempGraph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempGraph, &ui_font_displayRoboto18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_TempGraph, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_TempChart = lv_chart_create(ui_TempGraph);
    lv_obj_set_width(ui_TempChart, 617);
    lv_obj_set_height(ui_TempChart, 141);
    lv_obj_set_x(ui_TempChart, 6);
    lv_obj_set_y(ui_TempChart, -1);
    lv_obj_set_align(ui_TempChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_TempChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_TempChart, 12);
    lv_chart_set_range(ui_TempChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_axis_tick(ui_TempChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 24, 2, true, 25);
    lv_chart_set_axis_tick(ui_TempChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_TempChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_TempChart_series_1 = lv_chart_add_series(ui_TempChart, lv_color_hex(0x1CC7F3),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_TempChart_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_TempChart, ui_TempChart_series_1, ui_TempChart_series_1_array);
    lv_obj_set_style_bg_color(ui_TempChart, lv_color_hex(0x827A60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TempChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_set_style_text_font(ui_TempChart, &ui_font_displayRoboto18M, LV_PART_TICKS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TopButton11, ui_event_TopButton11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TopButton12, ui_event_TopButton12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TopButton13, ui_event_TopButton13, LV_EVENT_ALL, NULL);

}
